# -*- coding: utf-8 -*-
"""shopifystocks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WFSdLuCJxO-XF0zkiPCKGNo_RbEF1Jau
"""

from google.colab import drive
drive.mount('/content/drive')

file_path="/content/drive/MyDrive/shopify stocks.csv"

import pandas as pd
df = pd.read_csv(file_path)
df.head()

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns)
print("\nData Types:")
print(df.dtypes)
print("\nFirst 5 Rows:")
display(df.head())

print(df.isnull().sum())

price_columns = ['open', 'high', 'low', 'close', 'volume']
for column in price_columns:
    df[column] = pd.to_numeric(df[column], errors='coerce')

df = df.dropna(subset=price_columns)

df['date'] = pd.to_datetime(df['date'], errors='coerce', utc=True)
df = df.dropna(subset=['date'])
df = df.sort_values('date')
df = df.reset_index(drop=True)
df.head()

df['Daily_Delta'] = df['close'] - df['open']

print(df[['date', 'open', 'close', 'Daily_Delta']].head())

df['Daily_Return'] = df['close'].pct_change() * 100

print(df[['date', 'open', 'close', 'Daily_Delta', 'Daily_Return']].head())

print(df[['date', 'close', 'Daily_Return']].head())

print(df.columns.tolist())

average_volume = df['volume'].mean()
print("Average Trading Volume:", average_volume)

df['Volume_MA_20'] = df['volume'].rolling(20).mean()
print(df[['date', 'volume', 'Volume_MA_20']].head(25))

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))

plt.plot(df['date'], df['volume'], label='Daily Volume')
plt.plot(df['date'], df['Volume_MA_20'], label='20-Day Average Volume')

plt.title('Shopify Trading Volume Trend')
plt.xlabel('Date')
plt.ylabel('Trading Volume')

plt.legend()
plt.grid()

plt.show()

volume_mean = df['volume'].mean()
volume_std = df['volume'].std()

print("Average Trading Volume:", volume_mean)
print("Volume Standard Deviation:", volume_std)

high_volume_days = df[
    df['volume'] > volume_mean + 2 * volume_std
]

print("Anomalous Trading Days:")

display(
    high_volume_days[
        ['date', 'close', 'volume']
    ]
)

print("Number of Anomalous Trading Days:", len(high_volume_days))

returns = df['Daily_Return'].dropna()

print("Mean Return:", returns.mean())
print("Variance:", returns.var())
print("Standard Deviation:", returns.std())

print(df['Daily_Return'].describe())

plt.figure(figsize=(10, 5))

plt.hist(
    df['Daily_Return'].dropna(),
    bins=50
)

plt.title('Shopify Daily Return Distribution')
plt.xlabel('Daily Return (%)')
plt.ylabel('Frequency')

plt.grid()

plt.show()

print("Final Dataset:")

display(df.head())

print("Rows and Columns:")

print(df.shape)

print("Missing Values:")

print(df.isnull().sum())